#if !canImport(ObjectiveC)
import XCTest

extension GLAppBaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GLAppBaseTests = [
        ("testCreateApp", testCreateApp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GLAppBaseTests.__allTests__GLAppBaseTests),
    ]
}
#endif
