#if !canImport(ObjectiveC)
import XCTest

extension GLApplicationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GLApplicationTests = [
        ("testCreateApp", testCreateApp),
        ("testCreateAppSetRenderObject", testCreateAppSetRenderObject),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GLApplicationTests.__allTests__GLApplicationTests),
    ]
}
#endif
